# Generated by Django 5.2.1 on 2026-01-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_category_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
