# Generated by Django 5.2.1 on 2026-01-08 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_category_related_name'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='productinterest',
            new_name='shop_produc_user_id_ae4d3e_idx',
            old_name='shop_produc_user_id_0c66a5_idx',
        ),
        migrations.AddField(
            model_name='likedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='likedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='likedproduct',
            index=models.Index(fields=['user', 'created_at'], name='shop_likedp_user_id_a927c3_idx'),
        ),
        migrations.AddIndex(
            model_name='likedproduct',
            index=models.Index(fields=['product', 'created_at'], name='shop_likedp_product_705f82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likedproduct',
            unique_together={('user', 'product')},
        ),
    ]
